export enum ShoppingCategories {
  BAKED_GOODS = "BAKED_GOODS",
  BAKING_SUPPLIES = "BAKING_SUPPLIES",
  BEVERAGES = "BEVERAGES",
  CANNED_GOODS = "CANNED_GOODS",
  CEREAL = "CEREAL",
  CLEANING_SUPPLIES = "CLEANING_SUPPLIES",
  COFFEE_AND_TEA = "COFFEE_AND_TEA",
  CONDIMENTS = "CONDIMENTS",
  DAIRY = "DAIRY",
  DELI_MEATS = "DELI_MEATS",
  DRY_GOODS = "DRY_GOODS",
  FROZEN_FOODS = "FROZEN_FOODS",
  HEALTH_AND_BEAUTY = "HEALTH_AND_BEAUTY",
  HOME_IMPROVEMENT = "HOME_IMPROVEMENT",
  MEAT = "MEAT",
  PAPER_PRODUCTS = "PAPER_PRODUCTS",
  PET_SUPPLIES = "PET_SUPPLIES",
  PREPARED_FOODS = "PREPARED_FOODS",
  PRODUCE = "PRODUCE",
  SNACKS = "SNACKS",
  SPICES = "SPICES",
  VITAMINS_AND_SUPPLIMENTS = "VITAMINS_AND_SUPPLIMENTS",
}

export const shoppingCategoriesMap: Record<ShoppingCategories, string> = {
  [ShoppingCategories.BAKED_GOODS]: "Baked Goods",
  [ShoppingCategories.BAKING_SUPPLIES]: "Baking Supplies",
  [ShoppingCategories.BEVERAGES]: "Beverages",
  [ShoppingCategories.CANNED_GOODS]: "Canned Goods",
  [ShoppingCategories.CEREAL]: "Cereal",
  [ShoppingCategories.CLEANING_SUPPLIES]: "Cleaning Supplies",
  [ShoppingCategories.COFFEE_AND_TEA]: "Coffee & Tea",
  [ShoppingCategories.CONDIMENTS]: "Condiments",
  [ShoppingCategories.DAIRY]: "Dairy",
  [ShoppingCategories.DELI_MEATS]: "Deli Meats",
  [ShoppingCategories.DRY_GOODS]: "Dry Goods",
  [ShoppingCategories.FROZEN_FOODS]: "Frozen Foods",
  [ShoppingCategories.HEALTH_AND_BEAUTY]: "Health & Beauty",
  [ShoppingCategories.HOME_IMPROVEMENT]: "Home Improvment",
  [ShoppingCategories.MEAT]: "Meat",
  [ShoppingCategories.PAPER_PRODUCTS]: "Paper Products",
  [ShoppingCategories.PET_SUPPLIES]: "Pet Supplies",
  [ShoppingCategories.PREPARED_FOODS]: "Prepared Foods",
  [ShoppingCategories.PRODUCE]: "Produce",
  [ShoppingCategories.SNACKS]: "Snacks",
  [ShoppingCategories.SPICES]: "Spices",
  [ShoppingCategories.VITAMINS_AND_SUPPLIMENTS]: "Vitamins & Suppliments",
};
